### ISSUE TITLE
Running 'hence machine connect -i' fails when Docker is not installed

### ISSUE THREAD

**Issue by homertherefore** [hence-io/cli#3]
Upon a fresh use of the machine init steps, attempting to connect to the machine for the first time produced an error, due to not having docker on my machine.

``` bash
rm: /usr/local/bin/docker: No such file or directory
error: Process exited with a non-zero status.
```

**Comment by ghost** [comment]
Try latest version (0.0.10)  Should be fixed now.

**Comment by homertherefore** [comment]
That did the trick! Thanks @clintbeacock!
